### ISSUE TITLE
Install error - "AttributeError: module 'PyQt5.QtGui' has no attribute 'QAction'"

### ISSUE THREAD

**Issue by simplebutgood** [DOV-Vlaanderen/qgis-pixel-calculator#2]
Hi,
I am a bit of a QGIS noob, so apologies if this is a dumb question.
Can you help me address the error I get when trying to install: "AttributeError: module 'PyQt5.QtGui' has no attribute 'QAction'"?
Any tips appreciated.
CRAIG SHAW

Error log below (have used PROGRA-1 with hyphen instead of tilde to stop text here rendering as strikethrough):

Couldn't load plugin 'pixel_calculator' due to an error when calling its classFactory() method 

AttributeError: module 'PyQt5.QtGui' has no attribute 'QAction' 
Traceback (most recent call last):
  File "C:\PROGRA-1/QGIS 3.28.6/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/shawc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pixel_calculator\__init__.py", line 35, in classFactory
    from .pixel_calculator import PixelCalculator
  File "C:\PROGRA-1/QGIS 3.28.6/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/shawc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pixel_calculator\pixel_calculator.py", line 26, in 
    from .pixel_measure.action import PixelMeasureAction
  File "C:\PROGRA-1/QGIS 3.28.6/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/shawc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pixel_calculator\pixel_measure\action.py", line 7, in 
    class PixelMeasureAction(QtGui.QAction):
AttributeError: module 'PyQt5.QtGui' has no attribute 'QAction'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.28.6-Firenze Firenze, 868c9fa03b 

Python Path:
C:/PROGRA-1/QGIS 3.28.6/apps/qgis-ltr/./python
C:/Users/shawc/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/shawc/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA-1/QGIS 3.28.6/apps/qgis-ltr/./python/plugins
C:\PROGRA-1\QGIS 3.28.6\apps\grass\grass82\etc\python
C:\Users\shawc\Documents
C:\Program Files\QGIS 3.28.6\bin\python39.zip
C:\PROGRA-1\QGIS 3.28.6\apps\Python39\DLLs
C:\PROGRA-1\QGIS 3.28.6\apps\Python39\lib
C:\Program Files\QGIS 3.28.6\bin
C:\Users\shawc\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA-1\QGIS 3.28.6\apps\Python39
C:\PROGRA-1\QGIS 3.28.6\apps\Python39\lib\site-packages
C:\PROGRA-1\QGIS 3.28.6\apps\Python39\lib\site-packages\win32
C:\PROGRA-1\QGIS 3.28.6\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA-1\QGIS 3.28.6\apps\Python39\lib\site-packages\Pythonwin
C:/Users/shawc/AppData/Roaming/QGIS/QGIS3\profiles\default/python
.

**Comment by Roel** [comment]
Hi Craig,

Thank you for reporting this, there appeared to be an error in an import. This problem should be fixed in version 0.2.0, which will be available in QGis soon.

All the best,
Roel
